### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by MOONCHAND** [ParthS007/Loan-Approval-Prediction#1]
Sir I'm having an error in your code that is keyError and I'm unable to find what types of error it is?
Please help me sir!
The code is here.
![Screenshot (118)](https://user-images.githubusercontent.com/39911581/56507439-f0922c80-653e-11e9-85c3-7136d24bf75a.png)
please please help me sir!

**Comment by MOONCHAND** [comment]
And before "df['Self_Employed'].fillna('No',inplace =True)" There is no error at all.All are running similar as your code.
![Screenshot (119)](https://user-images.githubusercontent.com/39911581/56566702-efa9db00-65d0-11e9-814a-9c1c3fc582d0.png)

**Comment by MOONCHAND** [comment]
Please reply as soon as possible!

**Comment by ParthS007** [comment]
@MOONCHAND I am looking into it.

**Comment by MOONCHAND** [comment]
Sir,I think the KeyError is coming from "the reading training data set".Because I've seen your code there is no Disk drive mentioning to reading the training data set over there and I've mention Disk drive(F) to access the data set.Just have a look once.
![Screenshot (120)](https://user-images.githubusercontent.com/39911581/56655357-260a5780-66b0-11e9-9a99-38fe25ece411.png)

**Comment by handsometunex123** [comment]
I am experiencing the same issue. Please Parth help fix asap

**Comment by aeshna25** [comment]
@MOONCHAND even by specifying the disk drive, the error is the same. Did this work for you?

**Comment by aeshna25** [comment]
@ParthS007  when I ran ---- 
print(' Self_Employed ' in df.columns), the output was False. That means there is a possibility of whitespace in the respective column. Please reply if you fix the bug.

**Comment by MOONCHAND** [comment]
> 
> 
> @MOONCHAND even by specifying the disk drive, the error is the same. Did this work for you?

No not at all.I am getting keyError too.But in the code of Parth007 there is no Diskdrive mentioned and without mentioning diskdrive how to read the data that's confusing to me.I am not really sure but that's why we are getting errors.

**Comment by MOONCHAND** [comment]
Please reply sir as soon as possible.

**Comment by ParthS007** [comment]
Hello Everyone, I have gone through the error and I will fix it as soon as I get some time. I have my exams right now, will correct the error after exams and I will update you all here when I have fixed the error. 
Thanks for looking into my project. :)

**Comment by Sweety310897** [comment]
Did you resolve the issue. I have tried your code.Even I got the same error as MOONCHAND got. Can you please verify it.

**Comment by ParthS007** [comment]
solved in #3
