### ISSUE TITLE
n_folds

### ISSUE THREAD

**Issue by zachoid** [ParthS007/Loan-Approval-Prediction#2]
# Create logistic regression object
model = LogisticRegression()

# Train the model using the training sets
model.fit(x_train, y_train)

#Predict Output
predicted= model.predict(x_test)

#Reverse encoding for predicted outcome
predicted = number.inverse_transform(predicted)

#Store it to test dataset
test_modified['Loan_Status']=predicted

outcome_var = 'Loan_Status'

classification_model(model, df,predictors_Logistic,outcome_var)

test_modified.to_csv("Logistic_Prediction.csv",columns=['Loan_ID','Loan_Status'])``

its saying__init__() got an unexpected keyword argument 'n_folds'

**Comment by ParthS007** [comment]
fixed in #3
